---
abstract: 'We are Korean CPAN Authors! (우리는 CPAN Author 다!)'
author:
  - 'Jeen Lee <jeen@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-Korean
no_index:
  directory:
    - t
    - inc
requires:
  Acme::CPANAuthors: 0.02
  Test::More: 0.47
version: 0.10
