---
abstract: 'We are Korean CPAN Authors! (우리는 CPAN Author 다!)'
author:
  - 'Jeen Lee <jeen@perl.kr>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.5.6, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-Korean
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  Acme::CPANAuthors::Korean:
    file: lib/Acme/CPANAuthors/Korean.pm
    version: 0.11
requires:
  Acme::CPANAuthors: 0
  perl: 5.008001
resources:
  bugtracker: https://github.com/JEEN/p5-Acme-CPANAuthors-Korean/issues
  homepage: https://github.com/JEEN/p5-Acme-CPANAuthors-Korean
  repository: git://github.com/JEEN/p5-Acme-CPANAuthors-Korean.git
version: 0.11
x_contributors:
  - 'Keedi Kim <keedi.k@gmail.com>'
  - 'Jeen Lee <aiatejin@gmail.com>'
