---
abstract: 'We are Korean CPAN Authors!'
author:
  - 'JEEN <jeen@perl.kr>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Acme-CPANAuthors-Korean
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Acme::CPANAuthors: 0
  Filter::Util::Call: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/jeen/acme-cpanauthors-korean/tree/master
version: 0.03
